//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchanger.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documents()
        {
            this.Users = new HashSet<Users>();
        }
    
        public System.Guid Id { get; set; }
        public string FileName { get; set; }
        public int Size { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime LastEditDate { get; set; }
        public string CreatedBy { get; set; }
        public int AccessId { get; set; }
        public int FileTypeId { get; set; }
    
        public virtual Access Access { get; set; }
        public virtual FileType FileType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
